name: Deployement-to-zetsu-account
on:
  push: 
    branches:
      - main
permissions: 
  contents: write
jobs:
  deploy:
    name: run-on-machine
    runs-on: ubuntu-24.04

    steps:
      - name: chekout-repository-code-in-vm
        uses: actions/checkout@v4

      - name: ssh-deployement
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /var/www/blog/
            echo ${{ secrets.PASSWORD }} | sudo -S rm -rf .
            echo ${{ secrets.PASSWORD }} | sudo -S  git clone https://github.com/hnc450/site.git .
            echo ${{ secrets.PASSWORD }} | sudo -S rm -rf *.md *.txt .git .github
